### ISSUE TITLE
Cannot find module 'graphql'

### ISSUE THREAD

**Issue by gridworkz** [apollostack/frontpage-angular2-app#1]
Hi:
I get a number of errors as follows (after npm start):
......
ERROR in [default] /home/osboxes/projects/griderp-client/node_modules/apollo-client/queries/queryTransform.d.ts:1:39 
Cannot find module 'graphql'.

ERROR in [default] /home/osboxes/projects/griderp-client/node_modules/apollo-client/queries/store.d.ts:3:43 
Cannot find module 'graphql'.
.......
I've tried installing graphql both globally and locally but the apollo-client doesn't seem to pick it up.

Cheers,
Dave

**Comment by kamilkisiela** [comment]
Typescript is screaming about missing typings for `graphql`, not about not installed package called `graphql`. It works when you install typings (run `typings i` in terminal), but I've changed it in a30332f so only thing you will do (and every other user) will be `npm install` and that's it.
