### ISSUE TITLE
Apollo-client custom Headers in Angular2

### ISSUE THREAD

**Issue by PritiDawdaIntellect** [apollostack/frontpage-angular2-app#3]
How to add custom headers and introduce additional custom variables in request body using  apollo-client in Angular2. We wish to introduce an additional custom variable like default "Variables" object in request body along with custom headers before hitting graphQL server. I tried using applyMiddleware of createNetworkInterface in Angular 2, but it doesn't seem to work.

Below is expected request body format:
{
   "query":"",
   "variables":"{}",
   "customVariable":"{}", //This is additional which wants to be introduced
   "operationName":""
}

Request Headers must have custom headers:
req.options.headers.authorization = "custom header".

**Comment by Urigo** [comment]
@PritiDawdaIntellect can you please open this issue on our main repository?
https://github.com/apollostack/apollo-angular

It will be easier to track there

thanks
